name: Conditionals

on: [push]

jobs:

  my-conditional-job:
    if: github.repository != 'my-org/special-repo'
    runs-on: ubuntu-latest
    steps:
      - name: Run conditional task
        run: echo "This is a conditional task"

  my-normal-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run normal task
        run: echo "This is a normal task"