name: Scheduled Workflow
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
jobs:
  my-schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run scheduled task
        run: echo "This is a scheduled task running every five minutes."