name: Webhook
on:
  repository_dispatch:
    types:
      - webhook

jobs:
  my-webhook-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run webhook task
        run: echo "This is a webhook task $GITHUB_EVENT_NAME"