# DOCS: https://docs.github.com/en/actions/tutorials/publish-packages/publish-docker-images
name: Publish Docker image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@9f4a8ea54ed9055d5f86c993e1f2ffa674f98344
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@4f5b5234679dfa19837d4942067c97d7df43b7b3
        with:
          images: josecueva/github-actions-practice

      - name: Build and push Docker image
        uses: docker/build-push-action@789f68658055d3ca993799b232b5c46dfe3f114d
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}